# Generated by Django 2.0.2 on 2018-07-05 11:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import manageManga.funct


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(help_text='Este no se puede modificar luego.', upload_to=manageManga.funct.user_directory_path, verbose_name='PDF field')),
                ('user_chapter_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Chapter number')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(default='djangodbmodelsfieldsintegerfield', verbose_name='Slug')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
                'ordering': ['user_chapter_number'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.IntegerField(choices=[(1, 'Acción'), (2, 'Apocalíptico'), (3, 'Artes Marciales'), (4, 'Aventura'), (5, 'Ciencia Ficción'), (6, 'Comedia'), (7, 'Cyberpunk'), (8, 'Demonios'), (9, 'Deportes'), (10, 'Drama'), (11, 'Ecchi'), (12, 'Fantasía'), (13, 'Gender Bender'), (14, 'Gore'), (15, 'Harem'), (16, 'Histórico'), (17, 'Horror'), (18, 'Magia'), (19, 'Mecha'), (20, 'Militar'), (21, 'Misterio'), (22, 'Musical'), (23, 'Parodia'), (24, 'Policial'), (25, 'Psicológico'), (26, 'Realidad Virtual'), (27, 'Recuentos de la vida'), (28, 'Reencarnación'), (29, 'Romance'), (30, 'Samurai'), (31, 'Sobrenatural'), (32, 'Super Poderes'), (33, 'Supervivencia'), (34, 'Suspense'), (35, 'Tragedia'), (36, 'Vampiros'), (37, 'Vida Escolar'), (38, 'Yaoi'), (39, 'Yuri')], unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(39)])),
                ('name', models.CharField(default='DEFAULT', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('description', models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Description')),
                ('published_date_in_page', models.DateField(auto_now_add=True, verbose_name='Published Date')),
                ('slug', models.SlugField(default='djangodbmodelsfieldscharfield', max_length=100, unique=True, verbose_name='Slug')),
                ('verify', models.BooleanField(default=False, verbose_name='Verify')),
                ('puntaje', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Puntaje')),
                ('image', models.ImageField(upload_to='manga/portadas')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('genres', models.ManyToManyField(to='manageManga.Genre', verbose_name='Genres')),
            ],
            options={
                'verbose_name': 'Manga',
                'verbose_name_plural': 'Mangas',
                'ordering': ['-puntaje'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Numero de la Página')),
                ('image', models.ImageField(upload_to=manageManga.funct.user_directory_path)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageManga.Chapter', verbose_name='Capitulo')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, 'Emision'), (2, 'Finalizado'), (3, 'Pausado'), (4, 'Cancelado')], unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('name', models.CharField(default='DEFAULT', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tomo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(-1)], verbose_name='Numero del Tomo')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageManga.Manga', verbose_name='Manga')),
            ],
            options={
                'verbose_name': 'Tomo',
                'verbose_name_plural': 'Tomos',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_value', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Voto')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageManga.Manga', verbose_name='Manga')),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='manga',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageManga.State', verbose_name='State'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageManga.Manga', verbose_name='Manga'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='tomo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageManga.Tomo', verbose_name='Tomo'),
        ),
    ]
