# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 04:36
from __future__ import unicode_literals

from django.db import migrations, models
import manageManga.funct


class Migration(migrations.Migration):

    dependencies = [
        ('manageManga', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manga',
            options={'ordering': ['puntaje'], 'verbose_name': 'Manga', 'verbose_name_plural': 'Mangas'},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.FileField(upload_to=manageManga.funct.user_directory_path, verbose_name='Content'),
        ),
    ]
