# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 04:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageManga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='description',
            field=models.TextField(max_length=700, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='genres',
            field=models.ManyToManyField(to='manageManga.Genre', verbose_name='Genres'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='published_date',
            field=models.DateField(auto_now_add=True, verbose_name='Published Date'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageManga.State', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
