# Generated by Django 2.0.2 on 2018-02-15 05:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageManga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Numero de la Página')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageManga.Chapter', verbose_name='Página')),
            ],
        ),
    ]
