# Generated by Django 2.1 on 2018-08-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageManga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
