# Generated by Django 2.0.2 on 2018-04-09 05:00

from django.db import migrations, models
import manageManga.funct


class Migration(migrations.Migration):

    dependencies = [
        ('manageManga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.FileField(help_text='Este no se puede modificar luego.', upload_to=manageManga.funct.user_directory_path, verbose_name='PDF field'),
        ),
    ]
