# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 04:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageManga', '0002_auto_20180115_0436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manga',
            options={'ordering': ['-puntaje'], 'verbose_name': 'Manga', 'verbose_name_plural': 'Mangas'},
        ),
    ]
