# Generated by Django 2.0.2 on 2018-02-15 06:08

from django.db import migrations, models
import manageManga.funct


class Migration(migrations.Migration):

    dependencies = [
        ('manageManga', '0002_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(default=1, upload_to=manageManga.funct.page_path),
            preserve_default=False,
        ),
    ]
