# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageManga', '0002_auto_20171118_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Chapter number'),
        ),
        migrations.AddField(
            model_name='manga',
            name='chapters',
            field=models.TextField(blank=True, null=True, verbose_name='Chapters'),
        ),
    ]
