# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageManga', '0003_auto_20171119_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='chapters',
            field=models.TextField(blank=True, verbose_name='Chapters'),
        ),
    ]
