# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageManga', '0003_auto_20171110_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', max_length=100, verbose_name='Slug'),
        ),
    ]
