# Generated by Django 2.0.2 on 2018-02-15 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageManga', '0003_page_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['user_chapter_number'], 'verbose_name': 'Chapter', 'verbose_name_plural': 'Chapters'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['number'], 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
    ]
