# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 03:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageManga', '0004_auto_20171119_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='user_chapter_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Chapter number'),
            preserve_default=False,
        ),
    ]
