# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 23:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageManga', '0004_auto_20180125_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='description',
            field=models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(10, 'La descipcion debe tener al menos 10 caracteres.')], verbose_name='Description'),
        ),
    ]
