# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageManga', '0005_chapter_user_chapter_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='chapters',
        ),
        migrations.AddField(
            model_name='manga',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
