# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageManga', '0006_auto_20171119_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='verify',
            field=models.BooleanField(default=False, verbose_name='Verify'),
        ),
    ]
