# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageManga', '0006_auto_20180126_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='image',
            field=models.ImageField(upload_to='portadas'),
        ),
    ]
