# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageManga', '0007_auto_20180126_0104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='published_date',
            new_name='published_date_in_page',
        ),
        migrations.AlterField(
            model_name='manga',
            name='image',
            field=models.ImageField(upload_to='manga/portadas'),
        ),
    ]
