# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageManga', '0008_remove_chapter_chapter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name'),
        ),
    ]
