# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 02:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageManga', '0008_auto_20180126_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='puntaje',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Puntaje'),
        ),
    ]
