# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-27 22:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manageManga', '0009_auto_20180126_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tomo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Numero del Tomo')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageManga.Manga')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='tomo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manageManga.Tomo'),
            preserve_default=False,
        ),
    ]
