# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageManga', '0009_chapter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldsintegerfield', verbose_name='Slug'),
        ),
    ]
