# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-30 01:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageManga', '0010_auto_20180127_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tomo',
            options={'ordering': ['number'], 'verbose_name': 'Tomo', 'verbose_name_plural': 'Tomos'},
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='name',
        ),
        migrations.AlterField(
            model_name='tomo',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Numero del Tomo'),
        ),
    ]
