# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageManga', '0010_chapter_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Title'),
        ),
    ]
