# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-30 05:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageManga', '0011_auto_20180130_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tomo',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-1)], verbose_name='Numero del Tomo'),
        ),
    ]
