# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-24 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageManga', '0012_auto_20171216_0636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['slug'], 'verbose_name': 'Chapter', 'verbose_name_plural': 'Chapters'},
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='owner',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='manga',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Title'),
        ),
    ]
