# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 06:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('Acción', 'Acción'), ('Apocalíptico', 'Apocalíptico'), ('Artes Marciales', 'Artes Marciales'), ('Aventura', 'Aventura'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Comedia', 'Comedia'), ('Cyberpunk', 'Cyberpunk'), ('Demonios', 'Demonios'), ('Deportes', 'Deportes'), ('Drama', 'Drama'), ('Ecchi', 'Ecchi'), ('Fantasía', 'Fantasía'), ('Gender Bender', 'Gender Bender'), ('Gore', 'Gore'), ('Harem', 'Harem'), ('Histórico', 'Histórico'), ('Horror', 'Horror'), ('Magia', 'Magia'), ('Mecha', 'Mecha'), ('Militar', 'Militar'), ('Misterio', 'Misterio'), ('Musical', 'Musical'), ('Parodia', 'Parodia'), ('Policial', 'Policial'), ('Psicológico', 'Psicológico'), ('Realidad Virtual', 'Realidad Virtual'), ('Recuentos de la vida', 'Recuentos de la vida'), ('Reencarnación', 'Reencarnación'), ('Romance', 'Romance'), ('Samurai', 'Samurai'), ('Sobrenatural', 'Sobrenatural'), ('Super Poderes', 'Super Poderes'), ('Supervivencia', 'Supervivencia'), ('Suspense', 'Suspense'), ('Tragedia', 'Tragedia'), ('Vampiros', 'Vampiros'), ('Vida Escolar', 'Vida Escolar'), ('Yaoi', 'Yaoi'), ('Yuri', 'Yuri')], max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=700)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(default='djangodbmodelsfieldscharfield', max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('genders', models.ManyToManyField(to='createManga.Gender')),
            ],
            options={
                'verbose_name_plural': 'Mangas',
                'ordering': ['published_date'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, choices=[('Emision', 'Emision'), ('Finalizado', 'Finalizado'), ('Pausado', 'Pausado'), ('Cancelado', 'Cancelado')], max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='manga',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createManga.State'),
        ),
        migrations.AddField(
            model_name='comment',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createManga.Manga'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createManga.Manga'),
        ),
    ]
