# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 01:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createManga', '0002_auto_20171024_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='state',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
