# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createManga', '0003_auto_20171024_2054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentarios',
            new_name='Comment',
        ),
        migrations.AlterModelOptions(
            name='manga',
            options={},
        ),
    ]
