# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createManga', '0004_auto_20171024_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='published_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
